format = """
$directory$git_branch$git_commit$git_status$fill$time
$character
"""

add_newline = true

[directory]
style = "bold blue"
format = "[$path]($style) "
truncate_to_repo = false
truncation_length = 16
truncation_symbol = "…/"

[git_branch]
style = "bold green"
format = "[$branch]($style)"
only_attached = true

[git_commit]
style = "bold green"
format = "[$hash]($style)"

[git_status]
format = "[*]($style) "
style = 'bold green'

[fill]
symbol = " "

[time]
disabled = false
format = " [$time]($style)"
time_format = "%R"
style = "white"

[character]
format = "$symbol "
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
